site_name: practice_django

site_dir: 'wiki/GENERIC/generic/build'

nav:
  - django docs: django_docs.md
  - index: index.md
  - dev: dev.md
  - settings: settings.md
  - blog: blog/models.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode